import type {
  EventEdition,
  Groupbuy,
  NewsItem,
  Note,
} from "./types.ts";
import { generatedEvents } from "./generated/events.ts";

/** Product-validation fixtures retained for tests and migration reference only. */
export const exampleEvents: EventEdition[] = [
  {
    id: "illustar-2026-winter",
    slug: "illustar-fair",
    edition: "2026-winter",
    name: "일러스타페어 2026 겨울",
    shortName: "일러스타페어 겨울",
    organizer: "스타라이크",
    countryCode: "KR",
    countryName: "대한민국",
    city: "서울",
    timeZone: "Asia/Seoul",
    sourceLanguage: "ko",
    region: "서울",
    venue: "코엑스 D홀",
    address: "서울 강남구 영동대로 513",
    startDate: "2026-11-14T10:00:00+09:00",
    endDate: "2026-11-16T18:00:00+09:00",
    applicationOpen: "2026-07-10T10:00:00+09:00",
    applicationDeadline: "2026-08-07T12:00:00+09:00",
    boothFee: 180000,
    boothFeeCurrency: "KRW",
    boothSize: "1.8 × 0.9m",
    boothCount: 620,
    selection: "선착순",
    businessRequired: true,
    genre: "일러스트",
    scale: "대형",
    sourceUrl: "https://seoulillustrationfair.co.kr/",
    sourceLabel: "행사 공식 안내",
    verifiedAt: "2026-07-24",
    summary:
      "대형 일러스트·굿즈 행사. 신청 확정은 결제 완료 시점 기준이며, 통신판매업 신고 자료를 함께 확인해야 합니다.",
    application: {
      documents: ["사업자등록증", "통신판매업 신고증", "대표 이미지 3장"],
      resalePolicy: "본인 창작물만 허용",
      refundPolicy: "D-30까지 전액, 이후 50%, D-14 이후 환불 불가",
      note: "결제 완료 순서로 확정되는 선착순 접수",
    },
    onsite: {
      loadIn: "11.13 18:00–21:00 / 당일 08:00–09:30",
      loadOut: "11.16 18:00–21:00",
      electricity: "220V 1구, 사전 신청 ₩30,000",
      wallUse: null,
      parking: "코엑스 지하 주차, 일 최대 ₩25,000",
      logistics: "지하 하역장 → 화물 엘리베이터 → D홀",
      fixtures: "테이블 1, 의자 2 제공. 테이블보 미제공",
    },
    history: [
      {
        edition: "2026 겨울",
        dates: "11.14–11.16",
        venue: "코엑스 D홀",
        boothFee: 180000,
        previousBoothFee: 150000,
        booths: 620,
        selection: "선착순",
      },
      {
        edition: "2026 여름",
        dates: "05.23–05.25",
        venue: "코엑스 C홀",
        boothFee: 150000,
        booths: 540,
        selection: "선착순",
      },
      {
        edition: "2025 겨울",
        dates: "11.15–11.17",
        venue: "코엑스 C홀",
        boothFee: 150000,
        booths: 510,
        selection: "선착순",
      },
      {
        edition: "2025 여름",
        dates: "05.24–05.26",
        venue: "세텍 1관",
        boothFee: 120000,
        booths: 380,
        selection: "추첨",
      },
    ],
    reviewCount: 3,
  },
  {
    id: "seoul-illustration-2026-v20",
    slug: "seoul-illustration-fair",
    edition: "2026-v20",
    name: "서울일러스트레이션페어 V.20",
    shortName: "서일페 V.20",
    organizer: "오씨메이커스",
    countryCode: "KR",
    countryName: "대한민국",
    city: "서울",
    timeZone: "Asia/Seoul",
    sourceLanguage: "ko",
    region: "서울",
    venue: "코엑스 A홀",
    address: "서울 강남구 영동대로 513",
    startDate: "2026-12-05T10:00:00+09:00",
    endDate: "2026-12-08T18:00:00+09:00",
    applicationOpen: "2026-07-15T10:00:00+09:00",
    applicationDeadline: "2026-08-19T12:00:00+09:00",
    boothFee: 242000,
    boothFeeCurrency: "KRW",
    boothSize: "2.0 × 1.0m",
    boothCount: 900,
    selection: "추첨",
    businessRequired: true,
    genre: "복합",
    scale: "대형",
    sourceUrl: "https://seoulillustrationfair.co.kr/",
    sourceLabel: "서울일러스트레이션페어",
    verifiedAt: "2026-07-23",
    summary:
      "일러스트레이션과 디자인 굿즈 중심의 대형 페어. 포트폴리오와 판매 품목 검토 뒤 참가가 확정됩니다.",
    application: {
      documents: ["사업자등록증", "포트폴리오 URL", "판매 품목 목록"],
      resalePolicy: "창작자 본인의 작품과 정식 라이선스 상품",
      refundPolicy: "선정 통보 후 계약서 기준",
      note: "포트폴리오 검토 뒤 추첨 결과 안내",
    },
    onsite: {
      loadIn: "행사 전날 지정 시간대",
      loadOut: "마지막 날 18:30 이후",
      electricity: "사전 신청",
      wallUse: "지정 벽체만 가능",
      parking: "코엑스 주차 기준 적용",
      logistics: null,
      fixtures: "부스 유형별 상이",
    },
    history: [
      {
        edition: "V.20",
        dates: "12.05–12.08",
        venue: "코엑스 A홀",
        boothFee: 242000,
        booths: 900,
        selection: "추첨",
      },
      {
        edition: "V.19",
        dates: "07.24–07.27",
        venue: "코엑스 C홀",
        boothFee: 220000,
        booths: 820,
        selection: "심사",
      },
    ],
    reviewCount: 7,
    reviewAggregate: {
      valueForFee: 3.8,
      visitorDensity: 4.4,
      returnIntent: 82,
    },
  },
  {
    id: "mungu-box-2026-8",
    slug: "mungu-in-the-box",
    edition: "2026-8",
    name: "문구인더박스 8회",
    shortName: "문구인더박스 8회",
    organizer: "문구인더박스",
    countryCode: "KR",
    countryName: "대한민국",
    city: "부산",
    timeZone: "Asia/Seoul",
    sourceLanguage: "ko",
    region: "부산",
    venue: "벡스코 2전시장",
    address: "부산 해운대구 APEC로 55",
    startDate: "2026-12-19T10:00:00+09:00",
    endDate: "2026-12-21T18:00:00+09:00",
    applicationOpen: "2026-07-20T10:00:00+09:00",
    applicationDeadline: "2026-08-26T12:00:00+09:00",
    boothFee: 95000,
    boothFeeCurrency: "KRW",
    boothSize: "1.5 × 0.75m",
    boothCount: 180,
    selection: "선착순",
    businessRequired: false,
    genre: "문구",
    scale: "중형",
    sourceUrl: "https://www.bexco.co.kr/",
    sourceLabel: "벡스코 행사 안내",
    verifiedAt: "2026-07-22",
    summary:
      "문구와 소형 종이 제품에 집중한 부산 행사. 비사업자도 신청할 수 있어 첫 부스 후보로 비교하기 좋습니다.",
    application: {
      documents: ["대표 상품 이미지", "SNS 또는 판매 채널 URL"],
      resalePolicy: "직접 제작 또는 디자인한 문구 중심",
      refundPolicy: "마감 전 취소 수수료 없음, 이후 환불 규정 적용",
      note: "사업자 등록 여부와 무관하게 신청 가능",
    },
    onsite: {
      loadIn: "12.18 17:00–20:00",
      loadOut: "12.21 18:00–20:00",
      electricity: "유료 신청",
      wallUse: null,
      parking: "벡스코 참가자 주차권 별도",
      logistics: "2전시장 하역장 이용",
      fixtures: "테이블 1, 의자 1",
    },
    history: [
      {
        edition: "8회",
        dates: "12.19–12.21",
        venue: "벡스코 2전시장",
        boothFee: 95000,
        booths: 180,
        selection: "선착순",
      },
      {
        edition: "7회",
        dates: "06.13–06.15",
        venue: "벡스코 1전시장",
        boothFee: 90000,
        booths: 160,
        selection: "선착순",
      },
    ],
    reviewCount: 5,
    reviewAggregate: {
      valueForFee: 4.2,
      visitorDensity: 3.6,
      returnIntent: 88,
    },
  },
  {
    id: "daegu-illustration-2026",
    slug: "daegu-illustration-fair",
    edition: "2026",
    name: "대구 일러스트페어 2026",
    shortName: "대구 일러스트페어",
    organizer: "엑스코",
    countryCode: "KR",
    countryName: "대한민국",
    city: "대구",
    timeZone: "Asia/Seoul",
    sourceLanguage: "ko",
    region: "대구",
    venue: "엑스코 서관",
    address: "대구 북구 엑스코로 10",
    startDate: "2026-10-23T10:00:00+09:00",
    endDate: "2026-10-25T18:00:00+09:00",
    applicationOpen: "2026-08-01T10:00:00+09:00",
    applicationDeadline: "2026-09-04T18:00:00+09:00",
    boothFee: 140000,
    boothFeeCurrency: "KRW",
    boothSize: "1.8 × 0.9m",
    boothCount: 320,
    selection: "심사",
    businessRequired: false,
    genre: "일러스트",
    scale: "중형",
    sourceUrl: "https://www.exco.co.kr/",
    sourceLabel: "엑스코",
    verifiedAt: "2026-07-20",
    summary:
      "지역 창작자 비중이 높은 중형 행사. 접수 시작 전 포트폴리오와 판매 품목을 먼저 정리해 두는 편이 좋습니다.",
    application: {
      documents: ["포트폴리오", "판매 예정 품목"],
      resalePolicy: "창작물 중심",
      refundPolicy: "선정 이후 계약 기준",
      note: "8월 1일 접수 시작",
    },
    onsite: {
      loadIn: null,
      loadOut: null,
      electricity: "신청 가능 여부 확인 중",
      wallUse: null,
      parking: "엑스코 주차 기준",
      logistics: null,
      fixtures: null,
    },
    history: [
      {
        edition: "2026",
        dates: "10.23–10.25",
        venue: "엑스코 서관",
        boothFee: 140000,
        booths: 320,
        selection: "심사",
      },
    ],
    reviewCount: 0,
  },
  {
    id: "design-festa-2026",
    slug: "design-festa",
    edition: "2026",
    name: "서울 디자인페스타 2026",
    shortName: "디자인페스타",
    organizer: "디자인페스타 운영사무국",
    countryCode: "KR",
    countryName: "대한민국",
    city: "고양",
    timeZone: "Asia/Seoul",
    sourceLanguage: "ko",
    region: "경기",
    venue: "킨텍스 1전시장",
    address: "경기 고양시 일산서구 킨텍스로 217-60",
    startDate: "2026-08-08T10:00:00+09:00",
    endDate: "2026-08-10T18:00:00+09:00",
    applicationOpen: "2026-05-01T10:00:00+09:00",
    applicationDeadline: "2026-07-18T18:00:00+09:00",
    boothFee: 165000,
    boothFeeCurrency: "KRW",
    boothSize: "1.8 × 0.9m",
    boothCount: 410,
    selection: "심사",
    businessRequired: true,
    genre: "복합",
    scale: "대형",
    sourceUrl: "https://www.kintex.com/",
    sourceLabel: "킨텍스 행사 안내",
    verifiedAt: "2026-07-19",
    summary:
      "접수는 마감됐고 개최가 임박한 디자인 굿즈 행사. 참가 확정자는 반입 시간과 출입증 안내를 다시 확인해야 합니다.",
    application: {
      documents: ["사업자등록증", "제품 목록"],
      resalePolicy: "정식 유통 권한이 있는 상품만 허용",
      refundPolicy: "계약서 기준",
      note: "접수 마감",
    },
    onsite: {
      loadIn: "08.07 16:00–21:00",
      loadOut: "08.10 18:00–21:00",
      electricity: "사전 신청",
      wallUse: "기본 벽체 훼손 금지",
      parking: "참가자 등록 차량 할인",
      logistics: "1전시장 하역장 이용",
      fixtures: "테이블 1, 의자 2",
    },
    history: [
      {
        edition: "2026",
        dates: "08.08–08.10",
        venue: "킨텍스 1전시장",
        boothFee: 165000,
        booths: 410,
        selection: "심사",
      },
    ],
    reviewCount: 4,
  },
];

export const notes: Note[] = [
  {
    slug: "simple-tax-start",
    title: "간이과세자로 굿즈 판매를 시작할 때 확인할 것",
    category: "사업자·세금",
    tags: ["사업자", "부가세", "시작"],
    summary:
      "업종코드와 판매 채널을 먼저 정리하면 신고 방식과 증빙 준비가 한결 단순해집니다.",
    publishedAt: "2026-03-18",
    updatedAt: "2026-07-14",
    readMinutes: 8,
    isStale: false,
    legalNotice: true,
    sections: [
      {
        heading: "등록 전에 적어둘 것",
        paragraphs: [
          "판매할 품목, 주 판매 채널, 연간 예상 매출을 한 장에 적습니다. 이 세 값이 업종 선택과 과세 유형을 검토할 출발점입니다.",
          "행사 현장 판매와 온라인 판매를 함께 한다면 현금영수증, 카드 매출, 플랫폼 정산 내역을 같은 기준으로 모을 방법도 정합니다.",
        ],
      },
      {
        heading: "업종코드는 판매 방식과 함께 본다",
        paragraphs: [
          "굿즈의 제작 방식만 보고 제조업으로 단정하지 않습니다. 직접 제작과 외주 제작, 온라인 소매와 행사 판매가 섞이면 실제 운영 형태를 세무 전문가에게 설명하고 확인하는 편이 안전합니다.",
        ],
      },
    ],
    checklist: [
      "판매 품목과 채널을 한 줄로 설명할 수 있다.",
      "예상 매출과 주요 비용을 월 단위로 적었다.",
      "증빙을 저장할 폴더와 파일 이름을 정했다.",
      "최신 국세청 안내 또는 전문가 확인 일자를 기록했다.",
    ],
  },
  {
    slug: "reading-print-quotes",
    title: "인쇄 견적서 읽는 법 — 후가공 항목별 단가 구조",
    category: "제작·발주",
    tags: ["인쇄", "견적", "후가공"],
    summary:
      "박, 형압, 도무송, 코팅이 각각 어디에서 고정비와 수량비를 만드는지 구분합니다.",
    publishedAt: "2026-04-08",
    updatedAt: "2026-05-02",
    readMinutes: 10,
    isStale: false,
    legalNotice: false,
    sections: [
      {
        heading: "고정비와 수량비를 나눈다",
        paragraphs: [
          "목형, 동판, 칼선처럼 처음 한 번 발생하는 비용과 장당 가공비를 분리해 비교합니다. 수량만 바꾼 재견적을 받아 보면 어느 항목이 고정비인지 드러납니다.",
        ],
      },
      {
        heading: "비교표에 확인 시점을 쓴다",
        paragraphs: [
          "용지와 후가공 단가는 자주 변합니다. 업체명 옆에 견적을 받은 날짜와 부가세·배송비 포함 여부를 함께 적어야 다음 발주 때 비교할 수 있습니다.",
        ],
      },
    ],
    checklist: [
      "부가세 포함 여부를 확인했다.",
      "배송비와 포장비를 분리했다.",
      "목형·동판의 재사용 조건을 물었다.",
      "납기 기준일과 교정 횟수를 적었다.",
    ],
  },
  {
    slug: "first-booth-checklist",
    title: "첫 부스 준비물 체크리스트",
    category: "행사 운영",
    tags: ["행사", "부스", "체크리스트"],
    summary:
      "현장에서 되돌릴 수 없는 것부터 결제, 재고, 진열, 운반 순서로 점검합니다.",
    publishedAt: "2026-05-20",
    updatedAt: "2026-06-30",
    readMinutes: 7,
    isStale: false,
    legalNotice: false,
    sections: [
      {
        heading: "결제와 재고를 먼저 잠근다",
        paragraphs: [
          "거치대는 현장에서 빌릴 수 있어도 결제 수단과 가격표, 재고 수량은 대신 준비할 수 없습니다. 통신 상태가 좋지 않을 때 쓸 대체 결제 수단도 적어 둡니다.",
        ],
      },
      {
        heading: "운반 동선을 한 번 그린다",
        paragraphs: [
          "차량 하역장부터 부스까지 이동 경로, 엘리베이터, 대차 대여 위치를 확인합니다. 상자 수와 대차 횟수를 계산하면 반입 시간을 가늠할 수 있습니다.",
        ],
      },
    ],
    checklist: [
      "가격표와 품목별 재고표가 있다.",
      "카드·계좌·현금 대체 흐름을 정했다.",
      "반입 시간과 하역장 위치를 확인했다.",
      "마감 후 재고를 셀 방법을 정했다.",
    ],
  },
  {
    slug: "booth-break-even",
    title: "부스비를 회수하려면 몇 개를 팔아야 하나",
    category: "가격·원가",
    tags: ["원가", "행사", "손익분기"],
    summary:
      "부스비뿐 아니라 교통·숙박·제작 원가·재고 손실까지 포함한 손익분기 계산 틀입니다.",
    publishedAt: "2025-01-20",
    updatedAt: "2025-02-11",
    readMinutes: 9,
    isStale: true,
    legalNotice: false,
    sections: [
      {
        heading: "행사 고정비를 모두 모은다",
        paragraphs: [
          "부스비, 전기, 집기, 교통, 숙박, 식비를 행사 고정비로 묶습니다. 샘플 제작과 급행 인쇄가 있다면 별도 항목으로 남깁니다.",
        ],
      },
      {
        heading: "품목별 기여이익으로 나눈다",
        paragraphs: [
          "판매가에서 제작 원가와 결제 수수료를 뺀 금액이 품목 한 개의 기여이익입니다. 고정비를 평균 기여이익으로 나누면 필요한 판매 수량을 추정할 수 있습니다.",
        ],
      },
    ],
    checklist: [
      "행사 고정비를 빠짐없이 적었다.",
      "결제 수수료와 폐기율을 반영했다.",
      "낙관·기준·보수 세 시나리오를 만들었다.",
    ],
  },
];

export const groupbuys: Groupbuy[] = [
  {
    id: "gb-opp-5000",
    item: "OPP 접착 봉투 10×15 · 5,000매",
    category: "포장재",
    target: 25,
    current: 18,
    unit: "명",
    estimatedPrice: "1인 약 ₩18,400",
    deadline: "2026-08-01",
    status: "모집중",
    organizer: "종이상점",
    organizerHistory: { completed: 4, failed: 0 },
    settlement: "모집 마감 뒤 외부 안내 채널에서 계좌 정산",
    delivery: "총대 수령 후 국내 개별 배송",
  },
  {
    id: "gb-keyring-1000",
    item: "아크릴 키링 고리 · 은색 1,000개",
    category: "굿즈 부자재",
    target: 20,
    current: 8,
    unit: "명",
    estimatedPrice: "1인 약 ₩12,000",
    deadline: "2026-08-06",
    status: "모집중",
    organizer: "동그라미문구",
    organizerHistory: { completed: 2, failed: 1 },
    settlement: "참여 확정 뒤 외부 폼에서 안내",
    delivery: "서울 행사 현장 수령 또는 택배",
  },
  {
    id: "gb-display-15",
    item: "부스 3단 아크릴 거치대 공동 발주",
    category: "부스 집기",
    target: 15,
    current: 14,
    unit: "명",
    estimatedPrice: "1인 약 ₩31,000",
    deadline: "2026-07-28",
    status: "모집중",
    organizer: "모눈작업실",
    organizerHistory: { completed: 7, failed: 0 },
    settlement: "견적 확정 후 외부 연락처에서 정산",
    delivery: "제작업체 개별 배송",
  },
];

export const newsItems: NewsItem[] = [
  {
    id: "news-sif-participants",
    title: "서울일러스트레이션페어 참가자 프로필 공개 방식 확인",
    summary:
      "부스 번호, 대표 이미지, 소개, 외부 판매 채널을 참가자 페이지에서 함께 확인할 수 있습니다.",
    source: "서울일러스트레이션페어",
    sourceUrl: "https://seoulillustrationfair.co.kr/",
    publishedAt: "2026-07-24",
    category: "주최측 공지",
  },
  {
    id: "news-kif-process",
    title: "K-일러스트레이션페어 참가 신청 절차 갱신",
    summary:
      "포트폴리오 검수, 선납, 잔금, 대기 접수 순서를 신청 전에 확인해야 합니다.",
    source: "K-일러스트레이션페어",
    sourceUrl: "https://www.k-illustrationfair.com/page/41",
    publishedAt: "2026-07-21",
    category: "주최측 공지",
  },
  {
    id: "news-bexco-logistics",
    title: "벡스코 2전시장 반입 동선 안내 확인",
    summary:
      "차량 하역장과 전시장 출입 시간은 행사별로 달라 참가자 안내 원문을 다시 확인해야 합니다.",
    source: "벡스코",
    sourceUrl: "https://www.bexco.co.kr/",
    publishedAt: "2026-07-18",
    category: "현장 운영",
  },
  {
    id: "news-exco-calendar",
    title: "엑스코 하반기 전시 일정 페이지 갱신",
    summary:
      "대구권 행사 후보를 비교할 때 개최일과 참가 접수일을 별도로 기록해 두는 편이 안전합니다.",
    source: "엑스코",
    sourceUrl: "https://www.exco.co.kr/",
    publishedAt: "2026-07-15",
    category: "행사 일정",
  },
  {
    id: "news-creator-guide",
    title: "창작자 가이드의 예산·선물 구성 순서 참고",
    summary:
      "행사 준비 노트도 지원 전, 선정 후, 전날, 현장, 종료 후의 작업 순서로 다시 묶습니다.",
    source: "텀블벅 창작자 가이드",
    sourceUrl: "https://creator.tumblbug.com/",
    publishedAt: "2026-07-11",
    category: "실무 노트",
  },
];

export const events: EventEdition[] = generatedEvents;
export const regions = ["전체", ...new Set(events.map((event) => event.region))];
export const genres = ["전체", ...new Set(events.map((event) => event.genre))];
export const scales = ["전체", ...new Set(events.map((event) => event.scale))];
