-- Keep legacy event IDs valid for existing Binder links while adding the
-- first editor-checked official catalog generated by the content pipeline.
insert into public.community_event_allowlist (event_id, is_catalog) values
  ('illustration-korea-2026-seoul-at', true),
  ('illustration-korea-2026-incheon', true),
  ('illustration-korea-2026-suwon', true)
on conflict (event_id) do update set is_catalog = excluded.is_catalog;
